# Generated by Django 5.1.1 on 2024-11-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_bookinstance_date_borrowed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_mark_returned', 'Set book as returned')]},
        ),
    ]
