# Generated by Django 5.1.1 on 2024-11-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': [('can_mark_returned', 'Set book as returned'), ('add_author', 'Can add author'), ('change_author', 'Can change author'), ('delete_author', 'Can delete author')]},
        ),
    ]
