# Generated by Django 5.1.1 on 2024-11-20 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_bookinstance_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BelovedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beloved_by', to='catalog.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='beloved_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
