# Generated by Django 5.1.1 on 2024-11-20 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_belovedbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belovedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.book'),
        ),
    ]
